--- #YAML:1.0
name:               PDL-SVDLIBC
version:            0.08
abstract:           PDL interface to Doug Rohde's SVD C Library
author:
    - Bryan Jurish
license:            unknown
distribution_type:  module
configure_requires:
    Archive::Tar:         0
    Data::Dumper:         0
    ExtUtils::MakeMaker:  0
    File::Basename:       0
    PDL:                  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    PDL:  0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.57_05
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
